// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdv3jalAOuX-ERqqQAf9wY36PBIsMHRE',
    appId: '1:756024470515:web:06d4ea2bb35bd556c6c086',
    messagingSenderId: '756024470515',
    projectId: 'clot-86924',
    authDomain: 'clot-86924.firebaseapp.com',
    storageBucket: 'clot-86924.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSvVV_w1GygJOYBeoH6UWkxeI4z4ybeg',
    appId: '1:756024470515:android:af9935b6cf3b08b7c6c086',
    messagingSenderId: '756024470515',
    projectId: 'clot-86924',
    storageBucket: 'clot-86924.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GRa0-mRbpKV5YXGDheIr9mb_c-upTZc',
    appId: '1:756024470515:ios:c6aba5b62922d85dc6c086',
    messagingSenderId: '756024470515',
    projectId: 'clot-86924',
    storageBucket: 'clot-86924.firebasestorage.app',
    iosBundleId: 'com.example.clotShopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GRa0-mRbpKV5YXGDheIr9mb_c-upTZc',
    appId: '1:756024470515:ios:c6aba5b62922d85dc6c086',
    messagingSenderId: '756024470515',
    projectId: 'clot-86924',
    storageBucket: 'clot-86924.firebasestorage.app',
    iosBundleId: 'com.example.clotShopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkdv3jalAOuX-ERqqQAf9wY36PBIsMHRE',
    appId: '1:756024470515:web:4408a874116b8d80c6c086',
    messagingSenderId: '756024470515',
    projectId: 'clot-86924',
    authDomain: 'clot-86924.firebaseapp.com',
    storageBucket: 'clot-86924.firebasestorage.app',
  );
}
